#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: engine_engine client_client

engine_engine: 
	$(MAKE) -C engine all -f engine.cbp.mak

client_client: 
	$(MAKE) -C client all -f client.cbp.mak

clean: clean_engine_engine clean_client_client

clean_engine_engine: 
	$(MAKE) -C engine clean -f engine.cbp.mak

clean_client_client: 
	$(MAKE) -C client clean -f client.cbp.mak

.PHONY: clean_engine_engine clean_client_client

